title: PyTorch Lightning Basic GAN Tutorial
author: PL team
created: 2021-01-31
updated: 2021-02-23
license: CC
description: |
  How to train a GAN!

  Main takeaways:
  1. Generator and discriminator are arbitrary PyTorch modules.
  2. training_step does both the generator and discriminator training.
requirements:
  - torchvision
accelerator:
  - CPU
  - GPU
