title: Live DEMO for various domains
author: PL team
created: 2021-01-31
updated: 2021-02-23
license: CC
description: |
  Here are four examples using Lightning.

  1. MNIST
  2. GAN
  3. Finetuning a Transformer from Huggingface
  4. DQN
requirements:
  - gym
  - scikit-learn
  - torchvision
  - transformers
accelerator:
  - CPU
  - GPU
