trigger: none
pr:
  - main

#stages:
#- stage: testing

jobs:

  - job: nbval
    # how long to run the job before automatically cancelling
    timeoutInMinutes: 45
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: 2

    pool: gridai-spot-pool
    # this need to have installed docker in the base image...
    container:
      # base ML image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.8-torch1.7"
      # image: "pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime"
      options: "--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all"

    variables:
      ACCELERATOR: CPU,GPU
      PATH_DATASETS: "$(Build.Repository.LocalPath)/.datasets"

    steps:

    - bash: |
        lspci | egrep 'VGA|3D'
        whereis nvidia
        nvidia-smi
        python --version
      displayName: 'Image info & NVIDIA'

    - bash: |
        pip --version
        pip install --requirement requirements.txt
        pip list
      displayName: 'Install dependencies'

    - bash: |
        python -c "import torch ; mgpu = torch.cuda.device_count() ; assert mgpu > 0, f'GPU: {mgpu}'"
      displayName: 'Sanity check'

    - bash: |
        head=$(git rev-parse origin/main)
        git diff --name-only $head --output=master-diff.txt
        python .actions/helpers.py group-folders master-diff.txt
        echo "Changed folder:"
        cat changed-folders.txt
      displayName: 'Process folders'

    - script: |
        COUNT=$(python -c "lines = open('changed-folders.txt').readlines() ; print(len(lines))")
        echo "Chnaged folders: $COUNT"
        echo "##vso[task.setvariable variable=folders;isOutput=true]$COUNT"
      name: changed

    - script: |
        echo $(PATH_DATASETS)
        mkdir $(PATH_DATASETS)
        cd $(PATH_DATASETS)
        wget www.di.ens.fr/~lelarge/MNIST.tar.gz --progress=bar:force:noscroll
        tar -zxvf MNIST.tar.gz
        ls -l
      displayName: 'Pull datasets'

    - bash: |
        while IFS= read -r line; do
            bash .actions/ipynb-generate.sh $line
        done <<< $(cat changed-folders.txt)
      condition: gt(variables['changed.folders'], 0)
      displayName: 'Generate notebook'

    - bash: |
        while IFS= read -r line; do
            bash .actions/ipynb-test.sh $line
        done <<< $(cat changed-folders.txt)
      condition: and(succeeded(), gt(variables['changed.folders'], 0))
      displayName: 'PyTest notebook'
