name: Pe-Publish notebook

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  schedule:
    - cron: "0 0 * * *" # At the end of every day

jobs:
  generate-ipynb:
    runs-on: ubuntu-20.04
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    # timeout-minutes: 45
    env:
      PUB_BRANCH: publication
      ACCELERATOR: CPU
      PATH_DATASETS: "$GITHUB_ACTION_PATH/.datasets"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for all branches and tags
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Sanity branch check
        run: |
          echo $PUB_BRANCH
          git ls-remote --heads origin ${PUB_BRANCH} | grep ${PUB_BRANCH} >/dev/null
          if [ "$?" == "1" ] ; then echo "Branch doesn't exist"; exit; fi

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip --version
          pip install --requirement requirements.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip list
        shell: bash

      - name: Process folders
        run: |
          head=$(git rev-parse origin/$PUB_BRANCH)
          # todo: still missing past names for rename/modified
          git diff --name-only $head --output=master-diff.txt
          python .actions/helpers.py group-folders master-diff.txt
          echo "Changed folder:"
          cat changed-folders.txt
          echo "Dropped folder:"
          cat dropped-folders.txt
        shell: bash

      - name: ">> output"
        id: chnaged
        run: python -c "lines = open('changed-folders.txt').readlines(); print(f'::set-output name=dirs::{len(lines)}')"
      - name: ">> output"
        id: dropped
        run: python -c "lines = open('dropped-folders.txt').readlines(); print(f'::set-output name=dirs::{len(lines)}')"

      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.PAT_GHOST }}
          name: PL Ghost
          email: pl-github@grid.ai
      - name: Sync to pub
        run: |
          git checkout $PUB_BRANCH
          git merge -s resolve main

      - name: Generate notebook
        if: steps.chnaged.outputs.dirs != 0
        run: |
          while IFS= read -r line; do
              bash .actions/ipynb-generate.sh $line
          done <<< $(cat changed-folders.txt)
        shell: bash

      - name: Render notebook
        if: steps.chnaged.outputs.dirs != 0
        run: |
          # render the actual notebooks
          while IFS= read -r line; do
              bash .actions/ipynb-render.sh $line
          done <<< $(cat changed-folders.txt)
          git status
          git commit -m "publish [CPU]: ${{ github.event.head_commit.message }}"
        shell: bash

      - name: Prune notebook
        if: steps.dropped.outputs.dirs != 0
        run: |
          # remove notebooks which have moved
          while IFS= read -r line; do
              git rm .notebooks/$line.ipynb
          done <<< $(cat dropped-folders.txt)
          git status
          git commit -m "prune: ${{ github.event.head_commit.message }}"
        shell: bash

      - name: Finish push
        run: |
          git status
          git push
